spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
      routes:
        - id: modulo-pacientes
          uri: lb://MODULO-PACIENTES
          predicates:
           - Path=/api/pacientes/**
# Borra "/api/pacientes" de la URL antes de enviar la petición al microservicio
          filters:
          - StripPrefix=2 

        - id: modulo-atenciones
          uri: lb://MODULO-ATENCIONES
          predicates:
           - Path=/api/atenciones/**
# Borra "/api/atenciones" de la URL antes de enviar la petición al microservicio
          filters:
          - StripPrefix=2
    loadbalancer:
      ribbon:
        enabled: 'false'
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
# Ordena los servicios alfabéticamente en el menú desplegable
    operationsSorter: alpha
    tagsSorter: alpha
# Habilita la detección automática basada en las rutas de arriba
    use-root-path: true
    urls:
     - name: modulo-pacientes
       url: /api/pacientes/v3/api-docs
     - name: modulo-atenciones
       url: /api/atenciones/v3/api-docs