spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
      routes[0]:
        id: modulo-pacientes
        uri: lb://MODULO-PACIENTES
        predicates[0]: Path=/api/pacientes/**
      routes[1]:
        id: booking-microservice
        uri: lb://MODULO-ATENCIONES
        predicates[0]: Path=/api/atenciones/**
    loadbalancer:
      ribbon:
        enabled: 'false'
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/