spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maxi19/config-Server
          clone-on-start: true
          default-label: security
  security:
    user:
      name: configUser
      password: configPassword123
server:
  port: '8888'
---
spring:
  config:
    activate:
      on-profile: dev
eureka:
  client:
     service-url:
       defaultZone: http://eurekaUser:eurekaPassword123@localhost:8761/eureka/
  security:
    user:
      name: configUser
      password: configPassword123

---
spring:
  config:
    activate:
      on-profile: prod
eureka:
  client:
    service-url:
        defaultZone: http://eurekaProdUser:eurekaProdPassword123@eurekaserver:8761/eureka/
  security:
    user:
      name: configUser
      password: configPassword123