spring.application.name=configserver

server.port: 8888
spring.cloud.config.server.git.uri=https://github.com/maxi19/config-Server
#managment.endpoints.web.exposure.include=*
spring.cloud.config.server.git.clone-on-start=true
#define la rama
spring.cloud.config.server.git.default-label=main