spring.application.name=modulo-pacientes

spring.datasource.url=jdbc:mysql://localhost:3306/clinica
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.datasource.driverClassName=com.mysql.jdbc.Driver

server.port=8081
